#!/usr/bin/env bash
# bash script that infinitely displays a line, with sleep 2, and displays a line of text when it recieves a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2		
done 
 
