#!/usr/bin/env bash
# comment goes here
i = 1

while [ i -ls 10 ]

	do
	echo "Best School"

		if [ i -eq 4 ]
		echo "bad luck"
		
		elif [ i -eq 8 ]
		echo "good luck"

		else
		echp "Best School"

		((i++))
done
