#!/usr/bin/env bash
# comment goes here

i=1
	
while [ $i -le 20 ]

case $i in

		4) echo -n "bad luck from China"
		;;
		9) echo -n "bad luck from Japan"
		;;
		17) echo -n "bad luck from Italy"
		;;

	else 
	echo "Best School"
esac
