#!/usr/bin/env bash
# comment goes here

hour=0
minute=1

while [ $hour -lt 13 ]; do
	echo "Hour: $hour"
       	while [ $minute -lt 60 ]; do
		echo "$minute"
		((minute++))
	done
	((minute=1))
	((hours++))
done	




