#!/usr/bin/env bash
# comment goes here

hour=0
counter = 1

while [ $counter -le 60 ]

	do
		echo "$counter"
		((counter++))
			
			else [ $counter -eq 60 ]
			((hour++))
			echo "$hour
			counter = 1

	done
